server:
  port: 8444
  ssl:
    enabled: true
    key-store: classpath:keystore/reception.p12
    key-store-password: changeit
    key-store-type: PKCS12
    trust-store: classpath:keystore/truststore.jks
    trust-store-password: changeit

spring:
  datasource:
  # Reception does not use DB in first iteration (DB is used only by core), but we configure minimal
  jpa:
    hibernate:
      ddl-auto: none
logging:
  logger:
    hl7: INFO

reception:
  core-fhir-url: https://localhost:8443/fhir
  core-hl7-url: https://localhost:8443/hl7