server:
  port: 8445
  ssl:
    enabled: true
    key-store: classpath:keystore/doctor.p12
    key-store-password: changeit
    key-store-type: PKCS12
    trust-store: classpath:keystore/truststore.jks
    trust-store-password: changeit

logging:
  logger:
    hl7: TRACE

hospital:
  url: https://localhost:8443