spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hl7db}
    username: ${SPRING_DATASOURCE_USERNAME:hl7user}
    password: ${SPRING_DATASOURCE_PASSWORD:hl7pass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8081
logging:
  logger:
    hl7: TRACE