spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hl7db}
    username: ${SPRING_DATASOURCE_USERNAME:hl7user}
    password: ${SPRING_DATASOURCE_PASSWORD:hl7pass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore/hospital-chief.p12
    key-store-password: changeit
    key-store-type: PKCS12
    trust-store: classpath:keystore/truststore.jks
    trust-store-password: changeit

logging:
  logger:
    hl7: TRACE

doctor:
  url: https://localhost:8445