server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:file:./data-his/h2db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
hl7:
  listen-port: 2575
